
  test_pullrequest /home/runner/work/mlmodels/mlmodels/mlmodels/config/test_config.json Namespace(config_file='/home/runner/work/mlmodels/mlmodels/mlmodels/config/test_config.json', config_mode='test', do='test_pullrequest', folder=None, log_file=None, name='ml_store', save_folder='ztest/') 

  ml_test --do test_pullrequest 





 ********************************************************************************************************************************************

 ******** TAG ::  {'github_repo_url': 'https://github.com/arita37/mlmodels/tree/e8ed27623b3d1702165de43d885398f64d2c399e', 'url_branch_file': 'https://github.com/arita37/mlmodels/blob/dev/', 'repo': 'arita37/mlmodels', 'branch': 'dev', 'sha': 'e8ed27623b3d1702165de43d885398f64d2c399e', 'workflow': 'test_pullrequest'}

 ******** GITHUB_WOKFLOW : https://github.com/arita37/mlmodels/actions?query=workflow%3Atest_pullrequest

 ******** GITHUB_REPO_BRANCH : https://github.com/arita37/mlmodels/tree/dev/

 ******** GITHUB_REPO_URL : https://github.com/arita37/mlmodels/tree/e8ed27623b3d1702165de43d885398f64d2c399e

 ******** GITHUB_COMMIT_URL : https://github.com/arita37/mlmodels/commit/e8ed27623b3d1702165de43d885398f64d2c399e

 ******** Click here for Online DEBUGGER : https://gitpod.io/#https://github.com/arita37/mlmodels/tree/e8ed27623b3d1702165de43d885398f64d2c399e

 ************************************************************************************************************************

  /home/runner/work/mlmodels/mlmodels/pullrequest/ 

  ############Check model ################################ 

  ['/home/runner/work/mlmodels/mlmodels/pullrequest/aa_mycode_test.py'] 

  Used ['/home/runner/work/mlmodels/mlmodels/pullrequest/aa_mycode_test.py'] 

  ########### Run Check ############################## 





 ********************************************************************************************************************************************

 ******** TAG ::  {'github_repo_url': 'https://github.com/arita37/mlmodels/tree/e8ed27623b3d1702165de43d885398f64d2c399e', 'url_branch_file': 'https://github.com/arita37/mlmodels/blob/dev/', 'repo': 'arita37/mlmodels', 'branch': 'dev', 'sha': 'e8ed27623b3d1702165de43d885398f64d2c399e', 'workflow': 'test_pullrequest'}

 ******** GITHUB_WOKFLOW : https://github.com/arita37/mlmodels/actions?query=workflow%3Atest_pullrequest

 ******** GITHUB_REPO_BRANCH : https://github.com/arita37/mlmodels/tree/dev/

 ******** GITHUB_REPO_URL : https://github.com/arita37/mlmodels/tree/e8ed27623b3d1702165de43d885398f64d2c399e

 ******** GITHUB_COMMIT_URL : https://github.com/arita37/mlmodels/commit/e8ed27623b3d1702165de43d885398f64d2c399e

 ******** Click here for Online DEBUGGER : https://gitpod.io/#https://github.com/arita37/mlmodels/tree/e8ed27623b3d1702165de43d885398f64d2c399e

 ************************************************************************************************************************





 ********************************************************************************************************************************************

  test_import 
['model_rank.__init__', 'model_gluon.util_autogluon', 'model_gluon.gluonts_model', 'model_gluon.gluon_automl', 'model_gluon.util', 'model_gluon.gluonts_model_old', 'model_gluon.fb_prophet', 'model_gluon.__init__', 'utils.test_dataloader', 'utils.parse', 'utils.ztest_structure', 'model_tf.util', 'model_tf.__init__', 'model_tf.1_lstm', 'model_dev.temporal_fusion_google', 'model_dev.__init__', 'template.model_xxx', 'template.00_template_keras', 'model_keras.deepctr', 'model_keras.textcnn', 'model_keras.util', 'model_keras.charcnn_zhang', 'model_keras.preprocess', 'model_keras.charcnn', 'model_keras.namentity_crm_bilstm', 'model_keras.armdn', 'model_keras.Autokeras', 'model_keras.__init__', 'preprocess.text_keras', 'preprocess.text', 'preprocess.text_torch', 'preprocess.generic', 'preprocess.tabular', 'preprocess.timeseries', 'preprocess.image', 'preprocess.tabular_keras', 'preprocess.ztemp', 'preprocess.__init__', 'preprocess.generic_old', 'example.benchmark_timeseries_m5', 'example.vision_mnist', 'example.arun_model', 'example.benchmark_timeseries_m4', 'example.lightgbm_glass', 'example.arun_hyper', 'model_tch.transformer_sentence', 'model_tch.matchZoo', 'model_tch.textcnn', 'model_tch.util_data', 'model_tch.torchhub', 'model_tch.__init__', 'model_tch.util_transformer', 'model_sklearn.model_lightgbm', 'model_sklearn.__init__', 'model_sklearn.model_sklearn']
mlmodels.model_rank.__init__
mlmodels.model_gluon.util_autogluon

  Error mlmodels.model_gluon.gluonts_model invalid syntax (gluonts_model.py, line 203) 
/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/mxnet/optimizer/optimizer.py:167: UserWarning: WARNING: New optimizer gluonnlp.optimizer.lamb.LAMB is overriding existing optimizer mxnet.optimizer.optimizer.LAMB
  Optimizer.opt_registry[name].__name__))
/home/runner/work/mlmodels/mlmodels/mlmodels/model_gluon/gluonts_model_old.py:569: DeprecationWarning: invalid escape sequence \s
  """
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using CPU
Using TensorFlow backend.
/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning:

the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

/home/runner/work/mlmodels/mlmodels/mlmodels/preprocess/generic.py:736: DeprecationWarning:

invalid escape sequence \(

/home/runner/work/mlmodels/mlmodels/mlmodels/preprocess/generic.py:737: DeprecationWarning:

invalid escape sequence \)

/home/runner/work/mlmodels/mlmodels/mlmodels/preprocess/generic.py:738: DeprecationWarning:

invalid escape sequence \?

From /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
mlmodels.model_gluon.gluon_automl
mlmodels.model_gluon.util
mlmodels.model_gluon.gluonts_model_old
mlmodels.model_gluon.fb_prophet
mlmodels.model_gluon.__init__
mlmodels.utils.test_dataloader
mlmodels.utils.parse
mlmodels.utils.ztest_structure
mlmodels.model_tf.util
mlmodels.model_tf.__init__
mlmodels.model_tf.1_lstm

  Error mlmodels.model_dev.temporal_fusion_google No module named 'mlmodels.mode_tf' 
mlmodels.model_dev.__init__

  Error mlmodels.template.model_xxx invalid syntax (data.py, line 126) 

  Error mlmodels.template.00_template_keras expected an indented block (00_template_keras.py, line 68) 

  Error mlmodels.model_keras.deepctr cannot import name 'create_embedding_matrix' 
mlmodels.model_keras.textcnn
mlmodels.model_keras.util
/home/runner/work/mlmodels/mlmodels/mlmodels/dataset
mlmodels.model_keras.charcnn_zhang

  Error mlmodels.model_keras.preprocess cannot import name 'create_embedding_matrix' 
mlmodels.model_keras.charcnn
mlmodels.model_keras.namentity_crm_bilstm

  Error mlmodels.model_keras.armdn invalid syntax (data.py, line 126) 

  Error mlmodels.model_keras.Autokeras No module named 'autokeras' 
mlmodels.model_keras.__init__
mlmodels.preprocess.text_keras
mlmodels.preprocess.text

  Error mlmodels.preprocess.text_torch libtorch_cpu.so: cannot open shared object file: No such file or directory 
mlmodels.preprocess.generic
mlmodels.preprocess.tabular
mlmodels.preprocess.timeseries
mlmodels.preprocess.image

  Error mlmodels.preprocess.tabular_keras cannot import name 'create_embedding_matrix' 

  Error mlmodels.preprocess.ztemp invalid character in identifier (ztemp.py, line 6) 
mlmodels.preprocess.__init__
mlmodels.preprocess.generic_old

  Error mlmodels.example.benchmark_timeseries_m5 [Errno 2] File b'./m5-forecasting-accuracy/calendar.csv' does not exist: b'./m5-forecasting-accuracy/calendar.csv' 

  Error mlmodels.example.vision_mnist invalid syntax (vision_mnist.py, line 15) 
<module 'mlmodels' from '/home/runner/work/mlmodels/mlmodels/mlmodels/__init__.py'>
/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras/ardmn.json

  Error mlmodels.example.arun_model [Errno 2] No such file or directory: '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras/ardmn.json' 
mlmodels.example.benchmark_timeseries_m4
Deprecaton set to False
/home/runner/work/mlmodels/mlmodels

  Error mlmodels.example.lightgbm_glass [Errno 2] No such file or directory: 'lightgbm_glass.json' 

  Error mlmodels.example.arun_hyper name 'copy' is not defined 
PyTorch version 1.2.0 available.
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
mlmodels.model_tch.transformer_sentence
mlmodels.model_tch.matchZoo

  Error mlmodels.model_tch.textcnn libtorch_cpu.so: cannot open shared object file: No such file or directory 

  Error mlmodels.model_tch.util_data [Errno 2] File b'./data/train.csv' does not exist: b'./data/train.csv' 
mlmodels.model_tch.torchhub
mlmodels.model_tch.__init__
mlmodels.model_tch.util_transformer

  Error mlmodels.model_sklearn.model_lightgbm invalid syntax (model_lightgbm.py, line 319) 
Deprecaton set to False

  {'model_uri': 'model_tf.1_lstm', 'learning_rate': 0.001, 'num_layers': 1, 'size': 6, 'size_layer': 128, 'output_size': 6, 'timestep': 4, 'epoch': 2} {'data_path': '/home/runner/work/mlmodels/mlmodels/mlmodels/dataset/timeseries/GOOG-year_small.csv', 'data_type': 'pandas', 'size': [0, 0, 6], 'output_size': [0, 6]} {'engine': 'optuna', 'method': 'prune', 'ntrials': 5} {'engine_pars': {'engine': 'optuna', 'method': 'normal', 'ntrials': 2, 'metric_target': 'loss'}, 'learning_rate': {'type': 'log_uniform', 'init': 0.01, 'range': [0.001, 0.1]}, 'num_layers': {'type': 'int', 'init': 2, 'range': [2, 4]}, 'size': {'type': 'int', 'init': 6, 'range': [6, 6]}, 'output_size': {'type': 'int', 'init': 6, 'range': [6, 6]}, 'size_layer': {'type': 'categorical', 'value': [128, 256]}, 'timestep': {'type': 'categorical', 'value': [5]}, 'epoch': {'type': 'categorical', 'value': [2]}} 

  <module 'mlmodels.model_tf.1_lstm' from '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tf/1_lstm.py'> 

  ###### Hyper-optimization through study   ################################## 
[W 2020-09-06 12:24:23,990] Setting status of trial#0 as TrialState.FAIL because of the following error: UnboundLocalError("local variable 'module' referenced before assignment",)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/optuna/study.py", line 569, in _run_trial
    result = func(trial)
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 143, in objective
    module = model_create(module, model_pars, data_pars, compute_pars)  # module.Model(**param_dict)
UnboundLocalError: local variable 'module' referenced before assignment
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/bin/ml_optim", line 11, in <module>
    load_entry_point('mlmodels', 'console_scripts', 'ml_optim')()
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 382, in main
    test_json( path_json="template/optim_config_prune.json", config_mode= arg.config_mode )
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 230, in test_json
    out_pars        = out_pars
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 57, in optim
    out_pars)
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 170, in optim_optuna
    study.optimize(objective, n_trials=ntrials)  # Invoke optimization of the objective function.
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/optuna/study.py", line 302, in optimize
    gc_after_trial, None)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/optuna/study.py", line 538, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/optuna/study.py", line 550, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/optuna/study.py", line 569, in _run_trial
    result = func(trial)
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 143, in objective
    module = model_create(module, model_pars, data_pars, compute_pars)  # module.Model(**param_dict)
UnboundLocalError: local variable 'module' referenced before assignment
sh: 1: ml_mlmodels: not found
mlmodels.model_sklearn.__init__
mlmodels.model_sklearn.model_sklearn





 ********************************************************************************************************************************************

  python /home/runner/work/mlmodels/mlmodels/pullrequest/aa_mycode_test.py  2>&1 | tee -a  cd log_.txt 
os.getcwd /home/runner/work/mlmodels/mlmodels
############ Your custom code ################################



 python /home/runner/work/mlmodels/mlmodels/mlmodels/optim.py  
Deprecaton set to False

  {'model_uri': 'model_tf.1_lstm', 'learning_rate': 0.001, 'num_layers': 1, 'size': 6, 'size_layer': 128, 'output_size': 6, 'timestep': 4, 'epoch': 2} {'data_path': '/home/runner/work/mlmodels/mlmodels/mlmodels/dataset/timeseries/GOOG-year_small.csv', 'data_type': 'pandas', 'size': [0, 0, 6], 'output_size': [0, 6]} {'engine': 'optuna', 'method': 'prune', 'ntrials': 5} {'engine_pars': {'engine': 'optuna', 'method': 'normal', 'ntrials': 2, 'metric_target': 'loss'}, 'learning_rate': {'type': 'log_uniform', 'init': 0.01, 'range': [0.001, 0.1]}, 'num_layers': {'type': 'int', 'init': 2, 'range': [2, 4]}, 'size': {'type': 'int', 'init': 6, 'range': [6, 6]}, 'output_size': {'type': 'int', 'init': 6, 'range': [6, 6]}, 'size_layer': {'type': 'categorical', 'value': [128, 256]}, 'timestep': {'type': 'categorical', 'value': [5]}, 'epoch': {'type': 'categorical', 'value': [2]}} 

  <module 'mlmodels.model_tf.1_lstm' from '/home/runner/work/mlmodels/mlmodels/mlmodels/model_tf/1_lstm.py'> 

  ###### Hyper-optimization through study   ################################## 
[W 2020-09-06 12:24:27,135] Setting status of trial#0 as TrialState.FAIL because of the following error: UnboundLocalError("local variable 'module' referenced before assignment",)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/optuna/study.py", line 569, in _run_trial
    result = func(trial)
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 143, in objective
    module = model_create(module, model_pars, data_pars, compute_pars)  # module.Model(**param_dict)
UnboundLocalError: local variable 'module' referenced before assignment
Traceback (most recent call last):
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 394, in <module>
    main()
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 382, in main
    test_json( path_json="template/optim_config_prune.json", config_mode= arg.config_mode )
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 230, in test_json
    out_pars        = out_pars
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 57, in optim
    out_pars)
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 170, in optim_optuna
    study.optimize(objective, n_trials=ntrials)  # Invoke optimization of the objective function.
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/optuna/study.py", line 302, in optimize
    gc_after_trial, None)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/optuna/study.py", line 538, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/optuna/study.py", line 550, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/optuna/study.py", line 569, in _run_trial
    result = func(trial)
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/optim.py", line 143, in objective
    module = model_create(module, model_pars, data_pars, compute_pars)  # module.Model(**param_dict)
UnboundLocalError: local variable 'module' referenced before assignment



 python /home/runner/work/mlmodels/mlmodels/mlmodels/model_keras/textcnn.py    

  #### Module init   ############################################ 

  <module 'mlmodels.model_keras.textcnn' from '/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras/textcnn.py'> 

  #### Loading params   ############################################## 
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras/textcnn.py", line 258, in <module>
    test_module(model_uri = MODEL_URI, param_pars= param_pars)
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/models.py", line 257, in test_module
    model_pars, data_pars, compute_pars, out_pars = module.get_params(param_pars)
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/model_keras/textcnn.py", line 165, in get_params
    cf = json.load(open(data_path, mode='r'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/mlmodels/mlmodels/mlmodels/dataset/json/refactor/textcnn_keras.json'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/bin/ml_test", line 11, in <module>
    load_entry_point('mlmodels', 'console_scripts', 'ml_test')()
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/ztest.py", line 655, in main
    globals()[arg.do](arg)
  File "/home/runner/work/mlmodels/mlmodels/mlmodels/ztest.py", line 424, in test_pullrequest
    raise Exception(f"Unknown dataset type", x)
Exception: ('Unknown dataset type', '[W 2020-09-06 12:24:27,135] Setting status of trial#0 as TrialState.FAIL because of the following error: UnboundLocalError("local variable \'module\' referenced before assignment",)\n')
